Fix AggregateException when trying to fix xml version 1.1
vers-one/EpubReader pull request #38
Opened 2021-01-26 10:37 UTC by yunusefendi52

Fixes #34 

For some reason XDocument.Load changing the Position of the stream, so the fix is to make sure Position is resetted to 0

2022-02-24 02:18 UTC, vers-one requested changes
Thanks for reporting this issue and sorry for a delayed response!

I think it would be better to completely replace this whole try-catch-search for `1.1` approach with just reading the first line (using `StreamReader`) and if it turns out to be an XML 1.1 header, replace it with XML 1.0 header and then copy the rest of the stream.

Let me know if you want me to make this change or if you prefer to make it yourself in this pull request.

2022-03-02 15:11 UTC, yunusefendi52 commented
Agree, it would be better to replace try-catch-search with `StreamReader`. I think it would be better if you make that change with different branch though and this PR should be closed, but if you need some help with some testing I'd be happy to help :)

PS: I only meant to PR this https://github.com/vers-one/EpubReader/pull/38/commits/1bc9e9d13277de4934ff2e47e6b9b18f0f91e991 but somehow I also commit other "fix" for my use case

2022-03-03 03:42 UTC, vers-one commented
> I think it would be better if you make that change

Sure, will do. Thank you for bringing up this issue!

2022-03-06 07:30 UTC, closed without merging

2022-06-26 07:43 UTC, vers-one commented
Implemented in PR https://github.com/vers-one/EpubReader/pull/50.